// COMENTÁRIOS

// USE PARA COMENTÁRIOS PEQUENOS QUE FIQUEM APENAS E UMA LINHA

/*
    USE PARA COMENTÁRIOS
    MAIORES QUE FIQUE EM DIVERSAS LINHAS
*/

/*
    USE OS COMENTÁRIOS PARA ESPECIFICAR CADA PARTE DO SEU CÓDIGO,
    ISSO AJUDA PARA QUE OS OUTROS DESENVOLVEDORES QUE FOREM PARTICIPAR DE UM PROJETO COM VOCÊ INDENTIFIQUE MELHOR E MAIS RÁPIDO O QUE VOCÊ ESTÁ FAZENDO!
*/

const result = 2 + /*3 +*/ 4; // EU TAMBÉM CONSIGO COMENTAR DENTRO DE VARIÁVEIS OU FUNÇÕES, EM QUALQUER PARTE DO MEU CÓDIGO!
console.log(result)